### ISSUE TITLE
bug: Possible memory leak due to unclosed file

### ISSUE THREAD

**Issue by bohrium2b** [michaeldasheep/pastpapers-downloader#1]
https://github.com/michaeldasheep/cie-downloader/blob/27acad45e796a0be0fd7e0b094034d28e7a5ce3c/version2.py#L53

Hi Michael! I noticed that you opened configFile, but forgot to close it (unless I am missing something). This is a big no-no, as it can cause memory leaks and other bad stuff.

You might want to change it to
```python
with open("configV2.json", "r") as f:
    configFile = f.read()
```

**Comment by michaeldasheep** [comment]
Hi bohrium2b! Thank you for the report, I have added a close statement onto the code for v2, v1 and v11. Changes have been made and will be visible on the next commit.
